// TAB, TAB PANEL
export const MINI_MAP_TAB = "MiniMapTab"
export const MINI_MAP_PANEL = "MiniMapPanel"

export const PROFILE_TAB = "ProfileTab"
export const PROFILE_TAB_PANEL = "ProfileTabPanel"

export const PROJECT_TAB = "ProjectTab"
export const PROJECT_TAB_PANEL = "ProjectTabPanel"

export const PORTFOLIO_TAB = "PortfolioTab"
export const PORTFOLIO_TAB_PANEL = "PortfolioTabPanel"

export const FOLD_TAB = "foldTab"

export const CAREER_TAB = "CareerTab"
export const CAREER_TAB_PANEL = "CareerTabPanel"

export const MARKDOWN_TAB = "MARKDOWN_TAB"
export const MARKDOWN_TAB_PANEL = "MARKDOWN_TAB_PANEL"

export const MINI_BLOCK = "miniBlock"

// Setup
export const SETUP_BLOCK_EXPAND_ICON = "ExpandMoreIcon"
export const SETUP_BLOCK_TITLE = "BLOCK_TITLE"
export const SETUP_BLOCK = "SETUP_BLOCK"
// Field
export const INPUT_FIELD_TEST_ID = "INPUT_FIELD_TEST_ID"
export const DATE_FIELD_FROM_TEST_ID = "DATE_FIELD_FROM_TEST_ID"
export const DATE_FIELD_TO_TEST_ID = "DATE_FIELD_TO_TEST_ID"
export const IMAGE_FIELD_TEST_ID = "IMAGE_FIELD_TEST_ID"
export const AUTO_COMPLETE_FIELD_TEST_ID = "AUTO_COMPLETE_FIELD_TEST_ID"
export const MULTI_LINE_INPUT_FIELD_TEST_ID = "MULTI_LINE_INPUT_FIELD_TEST_ID"
export const SELECT_FIELD_TEST_ID = "SELECT_FIELD_TEST_ID"

// Layout
export const DEFINE_COLUMN_COUNT_SELECT = "DEFINE_COLUMN_COUNT_SELECT"
export const DEFINE_COLUMN_COUNT = "DEFINE_COLUMN_COUNT"
export const DEFINE_LAYOUT_TYPE = "DEFINE_LAYOUT_TYPE"

// PREVIEW
export const PREVIEW_CONTAINER = "PREVIEW_CONTAINER"
export const PROFILE_PREVIEW = "PROFILE_PREVIEW"
export const PROFILE_PREVIEW_MAIN_TEXT = "PROFILE_PREVIEW_MAIN_TEXT"
export const PROFILE_PREVIEW_SUB_TEXT = "PROFILE_PREVIEW_SUB_TEXT"

export const CAREER_PREVIEW = "CAREER_PREVIEW"

export const PROJECT_PREVIEW = "PROJECT_PREVIEW"
export const PROJECT_PREVIEW_NAME = "PROJECT_PREVIEW_NAME"
export const PROJECT_PREVIEW_ORGANIGATION = "PROJECT_PREVIEW_ORGANIGATION"
export const PROJECT_PREVIEW_TERM = "PROJECT_PREVIEW_TERM"
export const PROJECT_PREVIEW_DESCRIPTION = "PROJECT_PREVIEW_DESCRIPTION"
export const PROJECT_PREVIEW_SKILLS = "PROJECT_PREVIEW_SKILLS"

export const MARKDOWN_PREVIEW = "MARKDOWN_PREVIEW"

export const PORTFOLIO_PREVIEW = "PORTFOLIO_PREVIEW"
